// lib/personas.ts
// This file holds all our pre-built writing styles. It's separate
// so we can easily add, remove, or edit personas without touching the main app code.
import { Persona } from '@/types';

// We create an array of Persona objects, matching the shape defined in types/index.ts.
export const personas: Persona[] = [
  { id: 'david', name: 'Strategic Poet', description: 'For complex ideas & thought leadership.', promptFocus: 'Distill complex ideas into clear, impactful, and poetic language. Use strong assertions and metaphors. Do not use dashes.' },
  { id: 'ashley', name: 'Empathetic Connector', description: 'For community building & authentic connection.', promptFocus: 'Write with warmth, wit, and authentic emotion. Foster connection and understanding. Use inclusive language.' },
  { id: 'catalyst', name: 'The Catalyst', description: 'For marketing copy & persuasive calls-to-action.', promptFocus: 'Generate clear, concise, and persuasive copy. Focus on benefits over features and include a strong call-to-action.' },
  { id: 'scholar', name: 'The Scholar', description: 'For academic papers & formal reports.', promptFocus: 'Use formal, objective, and structured language. Maintain a scholarly tone and avoid colloquialisms.' },
  { id: 'chronicler', name: 'The Chronicler', description: 'For creative storytelling & evocative narratives.', promptFocus: 'Write descriptive, evocative, and narrative-driven prose. Use sensory details and build a compelling story arc.' },
  { id: 'sovereign', name: 'The Sovereign', description: 'For decisive leadership & setting vision.', promptFocus: 'Write with unwavering authority and clarity. Use direct, declarative statements. Project confidence and command. Eliminate all hedging language. The tone is final and visionary.' },
  { id: 'mentor', name: 'The Mentor', description: 'For guiding, teaching, and offering wisdom.', promptFocus: 'Write from a place of wisdom and experience. Explain complex topics patiently and clearly. Use analogies and guiding questions. The tone is encouraging, insightful, and trustworthy.' },
  { id: 'rebel', name: 'The Rebel', description: 'For challenging norms & disrupting conversation.', promptFocus: 'Write with a provocative and bold voice. Directly challenge a prevailing assumption or industry norm. The tone is unapologetic, confident, and disruptive. Question the status quo.' },
  { id: 'jester', name: 'The Jester', description: 'For engaging audiences with wit & humor.', promptFocus: 'Write with clever wit and a playful tone. Use irony, satire, or humor to make a point. The goal is to entertain, disarm the reader, and make the content highly memorable and shareable.' },
  { id: 'idealist', name: 'The Idealist', description: 'For inspiring with sincerity & optimism.', promptFocus: 'Write with genuine enthusiasm and unwavering optimism. The tone is sincere, hopeful, and deeply inspiring. Focus on the positive potential and the "why" behind the mission. Avoid all cynicism.' },
  { id: 'guardian', name: 'The Guardian', description: 'For support messages, customer service, & reassuring a team.', promptFocus: 'Write with a calming, supportive, and reassuring voice. Provide comfort and security. The language should be gentle, dependable, and focused on care and protection. The goal is to make the reader feel safe and supported.' },
  { id: 'alchemist', name: 'The Alchemist', description: 'For visionary pitches, transformational branding, & future-casting.', promptFocus: 'Write with a visionary and transformative tone. Frame the narrative around turning a grand vision into reality. Use powerful, evocative language that hints at a deeper, almost magical process of change. The goal is to inspire awe and belief in a future state.' },
  { id: 'artisan', name: 'The Artisan', description: 'For describing creative work, artistic statements, & design.', promptFocus: 'Write with a focus on craftsmanship, beauty, and the creative process. Use rich, sensory language and aesthetic metaphors. The tone is passionate, imaginative, and values originality and skill above all.' },
  { id: 'confidant', name: 'The Confidant', description: 'For personal letters, intimate posts, & building deep rapport.', promptFocus: 'Write with vulnerability, intimacy, and genuine appreciation. Use a personal, one-to-one tone as if speaking to a close friend. Focus on shared feelings and building deep, personal trust.' },
  { id: 'explorer', name: 'The Explorer', description: 'For travel logs, research journals, & exploring new ideas.', promptFocus: 'Write with a sense of wonder, curiosity, and discovery. Document a journey, whether physical or intellectual. The tone is open-minded, adventurous, and focuses on the thrill of the unknown and the process of learning.' },
];